version: '2'
services:
    message-server:
        container_name: agrocenter-server
        build:
            context: .
            dockerfile: Dockerfile
        image: message-server:latest
        ports:
            - 18080:8080
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge